# -*- coding: utf-8 -*-
"""customer choice.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_jAwayi4uXFOA6OUtW4IchqXqojpYerI
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

np.random.seed(42)

n = 300

data = pd.DataFrame({
      "age": np.random.randint(18, 60, n),
     "salary": np.random.randint(20000, 100000, n),
     "balance": np.random.randint(0, 200000, n)
})

# Create binary target
data["churn"] = (
     (data["balance"] > 100000).astype(int) |
     (data["salary"] < 40000).astype(int)
).astype(int)

data.head()

print(data.shape)
print(data.info())
print(data.describe())

print(data['churn'].value_counts())

import matplotlib.pyplot as plt

features = ["age", "salary", "balance"]

for col in features:
    plt.figure()
    plt.scatter(data[col], data["churn"])
    plt.xlabel(col)
    plt.ylabel("churn")
    plt.show()

X = data[["age", "salary", "balance"]]
y = data["churn"]

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

model = LogisticRegression(max_iter=1000)
model.fit(X_train, y_train)

y_pred = model.predict(X_test)
y_prob = model.predict_proba(X_test)[:, 1]

print("Accuracy:", accuracy_score(y_test, y_pred))
print("Confusion Matrix:\n", confusion_matrix(y_test, y_pred))
print("Classification Report:\n", classification_report(y_test, y_pred))
print("ROC-AUC:", roc_auc_score(y_test, y_prob))

coeff_df = pd.DataFrame({
    "Feature": X.columns,
    "Coefficient": model.coef_[0]
})

print(coeff_df)

new_data = pd.DataFrame({
    "age": [35],
    "salary": [30000],
    "balance": [150000]
})

print("churn prediction:", model.predict(new_data)[0])
print("probability:", model.predict_proba(new_data)[0][1])