# -*- coding: utf-8 -*-
"""Data Science

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1w6rE7coFxDOjIlUwygAsyRLCxMjYuH3P
"""

price=1000
discount=0.2
final_price=price-(price*discount)
tax_rate = 0.12
tax_amount = final_price * tax_rate
final_price_with_tax = final_price + tax_amount
print("Final price after discount and 18% tax:",final_price_with_tax)

customer_name = "Rahul" #string
age =25 #integer
salary = 55000.75 #float
is_fraud = False #boolean

print(f"Customer Name: {customer_name}")
print(f"Age: {age}")
print(f"Salary: {salary}")

# customer details
age =30
salary = 55000.0
loan_amount = 200000
existing_loans = 2
credit_score = 720
is_citizen = True

# ---Arithmetic Operators---
emi = loan_amount / 24 #Monthly installment
total_income_yearly = salary * 12
remaining_salary = total_income_yearly - (emi * 12)

print ("Monthly EMI:", emi)
print("Yearly Income:", total_income_yearly)
print("Remaining Salary after EMI:", remaining_salary)

# ---Comparison Operators ---
print ("Is credit score good?",credit_score>= 700)
print("Is EMI less than 50% of salary?", emi <(salary * 0.5))
print("Is age less than 60?", age <60)

# ---Logical Operators---
eligible = (credit_score >= 700) and (emi < (salary * 0.5)) and (age < 60)
print("Loan Eligibility :", eligible)

item1 =1200
item2 = 800
item3 = 600
discount = 0.1

total = item1 + item2 + item3
final_will = total -(total * discount)

print("Total Bill:", total)
print("Final Bill after discount:", final_will)

item1 =1200
item2 = 800
item3 = 600
discount = 0.1
tax = 0.10

total = item1 + item2 + item3
final_will = total -(total * discount)

print("Total Bill:", total)
print("Final Bill after discount:", final_will)

tax_amount = final_will * tax
print("Tax amount(18% GST):", tax_amount)

final_price = final_will + tax_amount
print("Final price after 18% GST:", final_price)

marks = int(input("Enter your score:"))
if marks >=90:
  print("Grade: A(kamal kar diya)")
elif marks >=75:
  print("Grade: B(KAATE PE HUA REE)")
elif marks <=35:
  print("Grade: D(FAIL HOGYA)")
else:
  print("Grade: C(thode se bacch gya)")

Customers = ["Rahul","Priya","Amit","Sneha","Vikram"]

for name in Customers:
  print("sending email to:",name)

for i in range(1 ,6):
  print("Reminder email number:", i)

students ={"Rahul":85, "Priya":34,"Amit":99}

for name, marks in students.items():
  if marks >=90:
    grade ="A"
  elif marks >= 75:
    grade = "B"
  else:
    grade = "C"
  print(f"Student: {name}, Marks:{marks}, Grade:{grade}")

def greet(name):
  print(" Hello ", name,"welcome to the bootcamp!")

greet("Amit")
greet("Samidha")

def Money(x,y):
  total=x+y
  return total

Money(1000,2000)
Money("abc","xyz")

#eligible for voting or not

def eligibility(age):
  print(age)
  if age>=18:
    print("ELIGIBLE FOR VOTING")
  else:
    print("NOT ELIGIBLE FOR VOTING")

eligibility(19)
eligibility(17)

import math
print("Square root of 25:",math.sqrt(25))
print("value of pi:",math.pi)

nums = [1,2,3]
mixed =[1,"a",True,2.14]
nested =[[1,2],[3,4]]
empty = list() #[]

a=[10,20,30,40,50]

a[0]     #10(first)

a[-1]      #50(last)

a[1:4]     #[20,30,40]  (copy)

a[::2]       #[10,30,50] (step)

a[::-1]       #reversed copy

a.append (60)           # add many
print(a)

a.extend ([70,80])       #add many
print(a)

a.remove  (30)           #remove first match
print(a)

val = a.pop()          #pop last   ->80
print(a)

idx =a.index(40)      #first index of value
print(a)

count = a.count(20)
print(a)

a .sort ()         #in-place sort
print(a)

b = sorted(a, reverse=True)    #new sorted list
print(b)

a.reverse()                #in-place reverse
print(a)

squares = [x*x for x in range (6)]
print(squares)

evens = [x for x in range(20) if x % 2 ==0]
print(evens)

from posixpath import join
pairs = [(i,j) for i in range(2) for j in range(2)]
print (pairs)

marks = [78,85,92,67,88]
print (marks)

# 1. Remove the lowest marks
marks.remove(min(marks))
print(marks)

# 2. Append a new marks
marks.append(90)
print(marks)

# 3. sort the list in descending order
marks.sort(reverse=True)
print(marks)

# 4. Take top 3 marks
top_3 = marks[:3]
print(marks)

# 5. Calculate average
average_top3 = sum(top_3) /len(top_3)

print ("Update Marks:",marks)
print("Top 3 Marks:", top_3)
print("Average of Top 3 Marks:", average_top3)
print(top_3)

emp = {"id":101,"name":"asha","dept":"HR"}
alt = dict(id=101,name="asha", dept="HR")
#empty = {}
print(emp)
print(alt)

emp["name"]                          #'asha' (keyError if missing)
emp . get("email")                    #None (safe)
emp. get("email","")                   #default value

emp["salary"] = 700000                 #add/update
emp.update({"dept":"HR Analytics","level":"senior"})

emp.popitem( )

emp.pop("x", None)

emp.pop("name", None)

import pandas as pd
import numpy as np

# sample dataset
data = {'Name':['Alice','Bob','Charlie','David'],
'age' : [25,np.nan, 30,np.nan],
'salary' :[50000,60000,  None , 45000]}

df = pd.DataFrame(data)
print("Before Cleaning:\n",df)

#Fill missing Salary with median
df['salary'] = df['salary'].fillna(df['salary'].median())
print('\nAfetr Cleaning:\n',df)

import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

#Example data
data = [10,12,13,12.11,200,14,13,15,12]

sns.boxplot(data)
plt.show()

#Detect using IOR
Q1 , Q3 = np.percentile(data,[25, 75])
IOR = Q3 -Q1
lower , upper = Q1 - 1.5 * IOR, Q3 + 1.5 * IOR
outliers = [x for x in data if x< lower or x> upper ]

print("outliers detected:",outliers)

from sklearn.preprocessing import MinMaxScaler, StandardScaler
import pandas as pd

df = pd.DataFrame({'Age':[18,22,30,40],'Salary':[20000,50000,80000,120000]})

# Normalization
scalar = MinMaxScaler()
df_norm = scalar.fit_transform(df)

#Standardization
scalar_std = StandardScaler()
df_std = scalar_std.fit_transform(df)

print("Original Data:\n",df)
print("\nNormalized Data:\n",df_norm)
print("\nStandardized Data:\n",df_std)

import pandas as pd
from sklearn.preprocessing import LabelEncoder

#Sample dataset
df = pd.DataFrame({
    'Name':['Alice','Bob','Charlie'],
    'Age': [25,30,35],
    'Country':['US','INDIA','US'],
    'Spend1':[200,150,300],
    'Spend2':[100,200,400]
})

#Feature Engineering: Total Spend
df['Total Spend'] = df['Spend1'] + df['Spend2']

#Feature Engineering: Age Group
df['Age Group'] = pd.cut(df['Age'], bins=[0,30,50], labels = ['Young','Middle'])

#Encode categorical feature
encoder = LabelEncoder()
df['Country_encoded'] = encoder.fit_transform(df['Country'])

print(df)

#Step 1 : Import & EDA
import pandas as pd

#Load dataset
df = pd.read_csv("/content/tips_dataset_350 (2) (1).csv")

#Quick look
print(df.head())
print(df.info())
print(df.describe())

#Check missing values
print(df.isnull().sum())

# EDA activities:

# Summary statistics
print('Summary Statistics:\n', df.describe())

# Distribution of numerical columns
import matplotlib.pyplot as plt
import seaborn as sns

plt.figure(figsize=(18, 5))

plt.subplot(1, 3, 1)
sns.histplot(df['total_bill'].dropna(), kde=True)
plt.title('Distribution of Total Bill')

plt.subplot(1, 3, 2)
sns.histplot(df['tip'].dropna(), kde=True)
plt.title('Distribution of Tip')

plt.subplot(1, 3, 3)
sns.histplot(df['size'].dropna(), kde=True)
plt.title('Distribution of Size')

plt.tight_layout()
plt.show()

# Fill with Mean (Numerical)
# df['Math_Score']=df['Math_Score'].fillna(df['Math_Score'].mean())

# Fill with Median
# df['Writing_Score']=df['Writing_Score'].fillna(df['Writing_Score'].median())

# Fill with Mode(Categorical)
# df['Parental_Education']=df['Parental_Education'].fillna(df['Parental_Education'].mode()[0])

# Fill with Mean (Numerical)
# df['Reading_Score']=df['Reading_Score'].fillna(df['Reading_Score'].mean())

name = input("Enter customer's name: ")
contact_no = input("Enter customer's contact number: ")

print(f"\nVerification code sent to {contact_no}.")

import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

df = pd.read_csv("/content/tips_dataset_350 (2) (1).csv")  # sample dataset

# Numerical variable
sns.histplot(df['total_bill'], kde=True)
plt.title('Distribution of Total Bill')
plt.show()

sns.boxplot(x=df["total_bill"])
plt.show()

# Categorical variable
sns.countplot(x="day", data=df)
plt.title('Sutej financial condition')
plt.show()

# Numerical vs Numerical
sns.scatterplot(x='total_bill', y='tip', data=df)
plt.title('Total Bill vs Tip')
plt.show()

# Categorical vs Numeri9cal
sns.boxplot(x='smoker', y='tip', data=df)
plt.title('Day vs Total Bill')
plt.show()

#Categorical vs Categorical
pd.crosstab(df['sex'], df['smoker'])
sns.heatmap(pd.crosstab(df['sex'], df['smoker']), annot=True, cmap='YlGnBu')
plt.title('Sex vs Smoker')
plt.show()

# Pairplot
sns.pairplot(df[['total_bill', 'tip', 'size']])
plt.show()

# Heatmap for correlation
sns.heatmap(df.select_dtypes(include=np.number).corr(), annot=True, cmap="coolwarm")
plt.show()

# Grouped boxplot
sns.boxplot(x="day", y="total_bill", hue="sex", data=df)
plt.title('Day vs Total Bill')
plt.show()



# Matplotlib basics
plt.plot(df["total_bill"])
plt.title("Line plot of Total bills")
plt.show()

# Matplotlib basics
plt.plot(df["smoker"])
plt.title("Line plot of smoker")
plt.show()

# Bar plot
plt.bar(df["day"].value_counts().index, df["day"].value_counts().values)
plt.title("Bar plot of Days")
plt.show()

# Pie chart
df["day"].value_counts().plot.pie(autopct="%1.1f%%")
plt.title("Pie chart of Days")
plt.show()



# Pie chart
df["smoker"].value_counts().plot.pie(autopct="%1.1f%%")
plt.title("Pie chart of Smoker")
plt.show()

# Descriptive statistics
print(df["total_bill"].describe())
print("skewness:",df["total_bill"].skew())
print("kurtosis:",df["total_bill"].kurt())

# Correlation
print(df.select_dtypes(include=np.number).corr())

# Simple regression
import statsmodels.api as sm

x=df["total_bill"]
y=df["tip"]
x=sm.add_constant(x)    # add intercept
model = sm.OLS(y,x).fit()
print(model.summary())

