# -*- coding: utf-8 -*-
"""student_clustering_project.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1YSXARiB2I_wN9FiJM3VZQHn7bgEKJnzK
"""

# step 1: Import Libraries
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.cluster import KMeans
from sklearn.metrics import silhouette_score

np.random.seed(42)

data = pd.DataFrame({
    "hours_studies": np.random.randint(1, 10, 50),
    "attendance": np.random.randint(50, 100,50)
})
data.head()

X = data[["hours_studies", "attendance"]]

model = KMeans(n_clusters=3, random_state=42, n_init=10)
data["cluster"] = model.fit_predict(X)

data.head()

score = silhouette_score(X, data["cluster"])
print("Silhouette Score:", score)

plt.scatter(data["hours_studies"], data["attendance"], c=data["cluster"])

centers = model.cluster_centers_
plt.scatter(centers[:, 0], centers[:, 1], marker="x", s=200)

plt.xlabel("Hours Studied")
plt.ylabel("Attendance")
plt.title("Student Segmentation")
plt.show()

# Example: New student
# hours_studies = 6, attendance = 80

new_student = [[6, 80]]\

predicted_cluster = model.predict(new_student)

print("New student belongs to cluster:", predicted_cluster[0])

data.groupby("cluster").mean()



